"""The parser, against markup nobody on this team wrote (STU-525).

Every other parse test feeds the parser markup we invented, so it can only
confirm shapes we already thought of. The corpus in tests/fixtures/markup/ is
harvested from the 16 real EPUBs on disk (gitignored: commercial, ~2.6 MB each):
tags, classes, charrefs and whitespace are byte-exact from the publisher's file,
the prose is replaced with filler.

Each shape is a pair: <name>.html is the snippet, <name>.txt the text the parser
must produce. The .txt is hand-written, never generated by the pipeline —
deriving it from the code under test is the circularity STU-524 removed from the
e2e fixture, and the assertion would then hold whatever the parser did.

Adding a book may surface conventions this corpus does not cover:

    python tests/fixtures/markup/harvest.py --library library/
"""
from pathlib import Path

import pytest
from bs4 import BeautifulSoup

from scripts.parse_epub import (
    _flatten_inline_markup,
    _mark_paragraph_breaks,
    _merge_block_dropcaps,
    clean_chapter_text,
)

CORPUS_DIR = Path(__file__).parent / "fixtures" / "markup"


def parse(html: str) -> str:
    """The production text path, as parse_epub wires it."""
    soup = BeautifulSoup(html, "html.parser")
    _flatten_inline_markup(soup)
    _merge_block_dropcaps(soup)
    _mark_paragraph_breaks(soup)
    return clean_chapter_text(soup.get_text(separator="\n", strip=True))


def _snippets():
    return sorted(CORPUS_DIR.glob("*.html"))


@pytest.mark.parametrize("html_path", _snippets(), ids=lambda p: p.stem)
def test_corpus_snippet_parses_to_expected_text(html_path):
    expected = html_path.with_suffix(".txt").read_text(encoding="utf-8").rstrip("\n")
    assert parse(html_path.read_text(encoding="utf-8")) == expected


def test_every_snippet_has_expected_text():
    """A snippet with no .txt would be collected and silently assert nothing."""
    orphans = [p.name for p in _snippets() if not p.with_suffix(".txt").exists()]
    assert not orphans


def test_corpus_covers_the_library():
    """A glob matching nothing would make the whole corpus vacuous."""
    assert len(_snippets()) >= 12


def test_snippets_carry_no_source_prose():
    """The snippets are structure, not the publisher's words."""
    forbidden = ("Eragon", "Palancar", "Nausica", "Alecto", "Kaladin", "Murtagh-",
                 "hobbit. Not a nasty", "Dras-Leona", "Isabella", "Saphira")
    for html_path in _snippets():
        html = html_path.read_text(encoding="utf-8")
        body = html.split("-->")[-1]  # attribution comments name their source book
        for word in forbidden:
            assert word not in body, f"{html_path.name} still carries source prose: {word}"
